def show_menu():
    print("\nBook Library Management System")
    print("==============================")
    print("1. Add Book")
    print("2. View All Books")
    print("3. Search Book")
    print("4. Update Book Details")
    print("5. Delete Book")
    print("6. Lend Book")
    print("7. Return Book")
    print("0. Exit")
